from __future__ import annotations

from typing import AsyncIterator, Protocol

from app.models.schemas import (
    ActivityEvent,
    Assessment,
    BuddyTurn,
    CandidateSession,
    EvaluationResult,
    Invite,
)


class Store(Protocol):
    async def startup(self) -> None: ...
    async def shutdown(self) -> None: ...

    async def put_assessment(self, assessment: Assessment) -> None: ...
    async def get_assessment(self, assessment_id: str) -> Assessment | None: ...
    async def list_assessments(self) -> list[Assessment]: ...

    async def put_session(self, session: CandidateSession) -> None: ...
    async def get_session(self, session_id: str) -> CandidateSession | None: ...
    async def list_sessions_for_assessment(self, assessment_id: str) -> list[CandidateSession]: ...

    async def append_event(self, event: ActivityEvent) -> None: ...
    async def get_events(self, session_id: str) -> list[ActivityEvent]: ...

    async def append_buddy_turn(self, session_id: str, turn: BuddyTurn) -> None: ...
    async def get_buddy_history(self, session_id: str) -> list[BuddyTurn]: ...

    async def put_evaluation(self, result: EvaluationResult) -> None: ...
    async def get_evaluation(self, session_id: str) -> EvaluationResult | None: ...

    async def put_invite(self, invite: Invite) -> None: ...
    async def get_invite(self, token: str) -> Invite | None: ...
    async def list_invites_for_assessment(self, assessment_id: str) -> list[Invite]: ...

    async def subscribe_assessment(self, assessment_id: str) -> AsyncIterator[Assessment]: ...
    async def subscribe_session(self, session_id: str) -> AsyncIterator[ActivityEvent]: ...
