"use client";

import { motion } from "framer-motion";
import {
  Database,
  Code2,
  TicketCheck,
  Bug,
  Compass,
  BarChart3,
} from "lucide-react";

const AGENTS = [
  {
    icon: Database,
    name: "Extractor",
    role: "Reads the team's Jira / Linear / GitHub to ground the assessment in real work.",
    accent: "from-violet/40 to-violet/0",
  },
  {
    icon: Code2,
    name: "Code Author",
    role: "Writes a production-grade golden artifact for the target role.",
    accent: "from-accent/40 to-accent/0",
  },
  {
    icon: TicketCheck,
    name: "Ticket Author",
    role: "Drafts the candidate-facing ticket and a hidden bug brief.",
    accent: "from-amber/40 to-amber/0",
  },
  {
    icon: Bug,
    name: "Bug Injector",
    role: "Plants realistic defects — the kind a real dev would write.",
    accent: "from-coral/40 to-coral/0",
  },
  {
    icon: Compass,
    name: "Buddy",
    role: "Hint-only Socratic tutor inside the candidate IDE. Never solves.",
    accent: "from-violet/40 to-violet/0",
  },
  {
    icon: BarChart3,
    name: "Evaluator",
    role: "Scores correctness + behaviour. Outputs a heatmap & a narrative.",
    accent: "from-accent/40 to-accent/0",
  },
];

export function AgentPipeline() {
  return (
    <section id="agents" className="relative py-28">
      <div className="mx-auto max-w-7xl px-6">
        <div className="max-w-2xl">
          <span className="text-xs uppercase tracking-[0.25em] text-accent">
            Six agents. One pipeline.
          </span>
          <h2 className="mt-3 font-display text-4xl md:text-5xl tracking-tight font-semibold leading-tight">
            Not a test bank.
            <br />
            <span className="text-bone/40">A miniature engineering org.</span>
          </h2>
          <p className="mt-5 text-bone/60 text-lg leading-relaxed">
            Each role-specific assessment is generated by a chain of specialised
            agents. The candidate experiences a real Jira ticket on a real codebase
            with realistic bugs — not a generic LeetCode prompt.
          </p>
        </div>

        <div className="mt-14 grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          {AGENTS.map((a, i) => {
            const Icon = a.icon;
            return (
              <motion.div
                key={a.name}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-80px" }}
                transition={{ delay: i * 0.06, duration: 0.5 }}
                whileHover={{ y: -4 }}
                className="group relative overflow-hidden rounded-2xl border border-black/[0.06] bg-ink-50 p-6 transition-colors hover:border-black/[0.12]"
              >
                <div
                  className={`absolute -top-20 -right-20 h-48 w-48 rounded-full bg-gradient-to-br ${a.accent} blur-3xl opacity-60 group-hover:opacity-100 transition-opacity`}
                />
                <div className="relative">
                  <div className="flex items-center gap-3">
                    <div className="grid place-items-center h-10 w-10 rounded-xl bg-black/5 border border-black/[0.06] group-hover:border-accent/40 transition">
                      <Icon className="h-5 w-5 text-bone/80 group-hover:text-accent transition" />
                    </div>
                    <div>
                      <div className="text-[10px] uppercase tracking-[0.2em] text-bone/40">
                        Agent {i + 1}
                      </div>
                      <div className="font-display text-lg font-semibold">{a.name}</div>
                    </div>
                  </div>
                  <p className="mt-4 text-sm text-bone/60 leading-relaxed">{a.role}</p>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
