import type { ReportData } from "./report-types";

const STARTED_AT = "2026-05-17T09:00:00Z";
const ENDED_AT = "2026-05-17T10:12:00Z";

export const MOCK_REPORT: ReportData = {
  available: true,
  header: {
    candidate_name: "Avery Chen",
    assessment_title: "Senior Backend Engineer — Payments",
    role_title: "Senior Backend Engineer",
    tech_stack: ["TypeScript", "Node.js", "PostgreSQL", "Redis"],
    seniority: "Senior",
    duration_used_min: 72,
    duration_allotted_min: 90,
    started_at: STARTED_AT,
    submitted_at: ENDED_AT,
    finished_early: true,
  },
  cq: {
    score: 78,
    summary:
      "Strong investigative behaviour and disciplined verification. AI usage was high-volume but consistently edited before commit. Missed one subtle race condition in the refund flow.",
    breakdown: {
      total: 78,
      components: [
        { key: "correctness", label: "Correctness", score: 22, max: 30, note: "Most cases covered; refund race left unhandled." },
        { key: "investigation", label: "Investigation", score: 18, max: 20, note: "Opened relevant files before editing; followed call graph cleanly." },
        { key: "ai_discipline", label: "AI Discipline", score: 14, max: 20, note: "Edited 4 of 6 accepted suggestions before commit." },
        { key: "verification", label: "Verification", score: 16, max: 20, note: "Ran tests after each fix; one untested edit." },
        { key: "communication", label: "Communication", score: 8, max: 10, note: "Concise strategy answers, clear trade-off framing." },
      ],
    },
  },
  metrics: [
    { key: "task_completion", label: "Task Completion", score: 8, max: 10 },
    { key: "code_quality", label: "Code Quality", score: 7, max: 10 },
    { key: "debugging", label: "Debugging", score: 9, max: 10 },
    { key: "ai_collaboration", label: "AI Collaboration", score: 7, max: 10 },
    { key: "ownership", label: "Ownership", score: 8, max: 10 },
  ],
  bug_exposure: {
    rows: [
      { id: "b1", bug_type: "off-by-one", description: "Pagination cursor skips last record on exact page boundary.", status: "fixed" },
      { id: "b2", bug_type: "null-deref", description: "Refund handler crashes when metadata is absent.", status: "fixed" },
      { id: "b3", bug_type: "race-condition", description: "Concurrent refunds can double-credit when retried.", status: "missed" },
      { id: "b4", bug_type: "validation", description: "Negative amount accepted in partial-refund path.", status: "noticed" },
      { id: "b5", bug_type: "logging", description: "PII leaks into error log when card token is invalid.", status: "encountered" },
    ],
    fixed_count: 2,
    missed_count: 1,
    total: 5,
  },
  ai: {
    prompts: [
      { at: "2026-05-17T09:04:11Z", content: "Explain how the refund retry queue is wired.", file_context: "src/payments/refund.ts", tags: ["explore"] },
      { at: "2026-05-17T09:17:42Z", content: "Why does test 'refund:partial' fail with NaN?", file_context: "src/payments/__tests__/refund.test.ts", tags: ["debug"] },
      { at: "2026-05-17T09:29:08Z", content: "Suggest a fix for the null metadata case.", file_context: "src/payments/refund.ts", tags: ["fix"] },
      { at: "2026-05-17T09:48:55Z", content: "Is there a cleaner way to express this guard?", file_context: "src/payments/validators.ts", tags: ["refactor"] },
      { at: "2026-05-17T10:02:14Z", content: "Write a test for negative-amount partial refunds.", file_context: "src/payments/__tests__/refund.test.ts", tags: ["test"] },
    ],
    prompt_count: 11,
    proposed: 6,
    accepted: 4,
    rejected: 2,
    blind_paste_rate: 0.17,
    edits_after_accept: 3,
    trap: {
      configured: true,
      bad_suggestion: "Use `parseInt(amount)` to coerce the refund amount.",
      trigger: "Refund amount parsing in src/payments/refund.ts",
      outcome: "passed",
    },
    model_used: "claude-sonnet-4-6",
  },
  behaviour: {
    timeline: [
      { label: "Opened repo", at: "2026-05-17T09:00:30Z", offset_pct: 0 },
      { label: "First file read", at: "2026-05-17T09:01:10Z", offset_pct: 2 },
      { label: "First edit", at: "2026-05-17T09:08:40Z", offset_pct: 12 },
      { label: "Ran tests", at: "2026-05-17T09:19:22Z", offset_pct: 27 },
      { label: "First commit", at: "2026-05-17T09:32:05Z", offset_pct: 44 },
      { label: "Submitted", at: ENDED_AT, offset_pct: 100 },
    ],
    files_before_first_edit: 7,
    time_to_first_edit_min: 8,
    total_files_opened: 19,
    investigation_note:
      "Read the call graph from API handler down to the refund queue before touching code. Returned to schema file twice while reasoning about idempotency.",
    heatmap_mix: { editor: 0.58, ai: 0.27, terminal: 0.15 },
    verification: { ran_tests: true, verified_ai_patches: true, small_commits: true },
  },
  integrity: {
    score: 92,
    flags: [
      { type: "tab_blur", label: "Tab switch", count: 3, total_duration_seconds: 41, details: "Brief switches to documentation tab." },
      { type: "large_paste", label: "Large paste", count: 1, total_duration_seconds: null, details: "180-char paste into refund.ts (matched an AI suggestion, edited after)." },
    ],
    disclaimer: "Integrity signals are advisory; investigate context before drawing conclusions.",
  },
  strategy: [
    {
      question: "How would you make the refund flow idempotent across retries?",
      answer:
        "Key on (charge_id, client_request_id) at the queue boundary, persist a refund_attempts row with a unique constraint, and short-circuit on duplicate insert. Settlement worker reads the row, not the queue payload.",
      score: 9,
      max: 10,
      note: "Identified the right boundary; missed mentioning DB-level isolation.",
      tags: ["idempotency", "queues"],
    },
    {
      question: "Where would you add observability before shipping?",
      answer:
        "A counter for refund_attempts by outcome, a histogram for queue→settlement latency, and a structured log on every state transition with the attempt id.",
      score: 8,
      max: 10,
      note: "Solid choices; no mention of alerting thresholds.",
      tags: ["observability"],
    },
  ],
  code_review: {
    summary:
      "Two small correctness wins, one missed concurrency hazard, and a logging change that risks PII. Overall the diff is tight and readable.",
    findings: [
      { severity: "critical", file: "src/payments/refund.ts", line: 142, message: "Concurrent refunds can double-credit; no DB-level guard on retry.", is_ai_generated_error: false },
      { severity: "warning", file: "src/payments/refund.ts", line: 88, message: "Negative amount path returns 200; should 422.", is_ai_generated_error: true },
      { severity: "warning", file: "src/payments/validators.ts", line: 23, message: "Guard accepts NaN as a valid amount.", is_ai_generated_error: false },
      { severity: "info", file: "src/payments/refund.ts", line: 201, message: "Error log includes raw card token — redact before emit.", is_ai_generated_error: false },
      { severity: "info", file: "src/payments/__tests__/refund.test.ts", line: 57, message: "Test name 'works' is non-descriptive.", is_ai_generated_error: false },
    ],
    critical_count: 1,
    warning_count: 2,
    info_count: 2,
  },
  activity_forensics: {
    total_events: 184,
    tracked_files: 4,
    file_summaries: [
      {
        file_path: "src/payments/refund.ts",
        active_seconds: 1420,
        total_events: 48,
        edit_events: 16,
        line_ranges: [
          { start_line: 34, end_line: 61, change_type: "replace" },
          { start_line: 118, end_line: 142, change_type: "insert" },
        ],
        first_at: "2026-05-17T09:04:08Z",
        last_at: "2026-05-17T10:09:44Z",
      },
    ],
    recent_entries: [
      {
        at: "2026-05-17T10:09:44Z",
        kind: "code_sync",
        file_path: "src/payments/refund.ts",
        line_start: 118,
        line_end: 142,
        summary: "Sandbox sync observed 14 added / 2 removed lines in L118-142.",
      },
    ],
  },
  buddy_audit: {
    total_messages: 10,
    blocked_messages: 0,
    proposed_edits: 4,
    applied_edits: 3,
    dismissed_edits: 1,
    transcript: [
      {
        at: "2026-05-17T09:04:11Z",
        role: "user",
        content: "Explain how the refund retry queue is wired.",
        challenge_id: "CHL_demo_1",
        open_file: "src/payments/refund.ts",
        blocked: false,
        hint_level: null,
        edit_targets: [],
      },
      {
        at: "2026-05-17T09:04:19Z",
        role: "buddy",
        content: "Start at the API handler, then follow the enqueue helper into the worker.",
        challenge_id: "CHL_demo_1",
        open_file: "src/payments/refund.ts",
        blocked: false,
        hint_level: "guide",
        edit_targets: ["src/payments/refund.ts"],
      },
    ],
    actions: [
      {
        at: "2026-05-17T09:29:40Z",
        action: "applied",
        file_path: "src/payments/refund.ts",
        challenge_id: "CHL_demo_1",
        rationale: "Added a null guard before metadata access.",
      },
    ],
  },
  feedback_log: [
    {
      id: "FDB_demo_1",
      category: "workspace",
      message: "The terminal lagged for about a minute after opening the coding challenge.",
      challenge_id: "CHL_demo_1",
      status: "open",
      created_at: "2026-05-17T09:26:12Z",
    },
  ],
  playback_url: "#",
  behaviour_analytics: {
    per_ticket: [
      {
        ticket_id: "TKT_a1b2c3d4e5",
        ticket_title: "Make refund flow idempotent across retries",
        story_points: 5,
        total_seconds: 1860,
        active_seconds: 1410,
        idle_seconds: 240,
        ai_seconds: 210,
        focus_periods: 3,
        stuck_flag: false,
      },
      {
        ticket_id: "TKT_f6g7h8i9j0",
        ticket_title: "Reject negative amounts in partial refund",
        story_points: 2,
        total_seconds: 720,
        active_seconds: 540,
        idle_seconds: 90,
        ai_seconds: 90,
        focus_periods: 2,
        stuck_flag: false,
      },
      {
        ticket_id: "TKT_k1l2m3n4o5",
        ticket_title: "Redact PII from error logs",
        story_points: 3,
        total_seconds: 1080,
        active_seconds: 360,
        idle_seconds: 600,
        ai_seconds: 120,
        focus_periods: 4,
        stuck_flag: true,
      },
    ],
    idle: {
      total_idle_seconds: 930,
      idle_percentage: 22,
      think_pause_count: 11,
      extended_idle_count: 4,
      inactive_count: 1,
      idle_after_ai_suggestion: 3,
      longest_episode: {
        at: "2026-05-17T09:38:12Z",
        duration_seconds: 380,
        tier: "inactive",
        preceding_activity: "ai",
        following_activity: "editor",
        note: "Followed AI patch proposal — likely reviewing suggestion.",
      },
      episodes: [
        {
          at: "2026-05-17T09:22:40Z",
          duration_seconds: 120,
          tier: "extended_idle",
          preceding_activity: "ticket",
          following_activity: "editor",
          note: "Followed ticket read — likely planning the next change.",
        },
        {
          at: "2026-05-17T09:38:12Z",
          duration_seconds: 380,
          tier: "inactive",
          preceding_activity: "ai",
          following_activity: "editor",
          note: "Followed AI patch proposal — likely reviewing suggestion.",
        },
        {
          at: "2026-05-17T09:51:05Z",
          duration_seconds: 95,
          tier: "extended_idle",
          preceding_activity: "terminal",
          following_activity: "editor",
          note: "Followed terminal output — likely reading results.",
        },
        {
          at: "2026-05-17T10:04:30Z",
          duration_seconds: 145,
          tier: "extended_idle",
          preceding_activity: "editor",
          following_activity: "ai",
          note: "Extended idle — possibly stuck or deep in thought.",
        },
        {
          at: "2026-05-17T10:08:10Z",
          duration_seconds: 80,
          tier: "extended_idle",
          preceding_activity: "editor",
          following_activity: "terminal",
          note: "Extended idle — possibly stuck or deep in thought.",
        },
      ],
    },
    keystrokes: {
      total_keystrokes: 4280,
      average_wpm: 42,
      peak_wpm: 78,
      undo_count: 18,
      paste_vs_type_ratio: 0.09,
      delete_ratio: 0.12,
      dominant_pattern: "think-then-type",
      wpm_sparkline: [
        0, 22, 35, 48, 51, 30, 12, 28, 44, 62, 70, 58, 36, 18, 8, 14, 32, 50,
        66, 78, 70, 42, 30, 24, 12, 0, 18, 36, 52, 60, 48, 32, 20, 14, 26, 38,
        44, 30, 12, 6,
      ],
    },
    content_attribution: {
      files: [
        {
          file_path: "src/payments/refund.ts",
          total_lines: 142,
          manual_pct: 38,
          ai_patch_pct: 35,
          pasted_pct: 14,
          unchanged_pct: 13,
        },
        {
          file_path: "src/payments/validators.ts",
          total_lines: 64,
          manual_pct: 56,
          ai_patch_pct: 20,
          pasted_pct: 6,
          unchanged_pct: 18,
        },
        {
          file_path: "src/payments/__tests__/refund.test.ts",
          total_lines: 88,
          manual_pct: 22,
          ai_patch_pct: 48,
          pasted_pct: 22,
          unchanged_pct: 8,
        },
        {
          file_path: "src/queue/worker.ts",
          total_lines: 96,
          manual_pct: 4,
          ai_patch_pct: 8,
          pasted_pct: 6,
          unchanged_pct: 82,
        },
      ],
      overall_manual_pct: 33,
      overall_ai_patch_pct: 31,
      overall_pasted_pct: 14,
      overall_unchanged_pct: 22,
    },
    focus: {
      panel_time: {
        editor: 2640,
        ai: 720,
        tickets: 360,
        terminal: 480,
        git: 120,
      },
      ticket_rereads: 5,
      longest_editor_stretch_seconds: 540,
      window_blur_count: 3,
      window_blur_total_seconds: 41,
      most_edited_file: "src/payments/refund.ts",
      file_visit_order: [
        "src/payments/refund.ts",
        "src/payments/validators.ts",
        "src/queue/worker.ts",
        "src/db/schema.sql",
        "src/payments/__tests__/refund.test.ts",
      ],
      transitions: [
        { from: "editor", to: "ai", count: 14 },
        { from: "ai", to: "editor", count: 12 },
        { from: "tickets", to: "editor", count: 9 },
        { from: "editor", to: "tickets", count: 5 },
        { from: "editor", to: "terminal", count: 7 },
        { from: "terminal", to: "editor", count: 7 },
      ],
    },
    phases: {
      phases: [
        {
          phase: "exploration",
          start_at: STARTED_AT,
          end_at: "2026-05-17T09:09:00Z",
          duration_seconds: 540,
          confidence: 0.78,
          signals: ["file reads outpaced edits"],
        },
        {
          phase: "planning",
          start_at: "2026-05-17T09:09:00Z",
          end_at: "2026-05-17T09:13:00Z",
          duration_seconds: 240,
          confidence: 0.62,
          signals: ["think pauses + AI architecture prompts"],
        },
        {
          phase: "execution",
          start_at: "2026-05-17T09:13:00Z",
          end_at: "2026-05-17T09:46:00Z",
          duration_seconds: 1980,
          confidence: 0.81,
          signals: ["keystrokes + edits dominated"],
        },
        {
          phase: "verification",
          start_at: "2026-05-17T09:46:00Z",
          end_at: "2026-05-17T09:54:00Z",
          duration_seconds: 480,
          confidence: 0.74,
          signals: ["terminal/commit activity"],
        },
        {
          phase: "execution",
          start_at: "2026-05-17T09:54:00Z",
          end_at: "2026-05-17T10:07:00Z",
          duration_seconds: 780,
          confidence: 0.7,
          signals: ["keystrokes + edits dominated"],
        },
        {
          phase: "verification",
          start_at: "2026-05-17T10:07:00Z",
          end_at: ENDED_AT,
          duration_seconds: 300,
          confidence: 0.69,
          signals: ["terminal/commit activity"],
        },
      ],
      time_in_exploration: 540,
      time_in_planning: 240,
      time_in_execution: 2760,
      time_in_verification: 780,
      phase_sequence: "E → P → Ex → V → Ex → V",
      has_verification_phase: true,
      exploration_before_execution: true,
    },
  },
  heatmap: {
    buckets: 12,
    bucket_seconds: 360,
    files: [
      "src/payments/refund.ts",
      "src/payments/validators.ts",
      "src/payments/__tests__/refund.test.ts",
      "src/queue/worker.ts",
      "src/db/schema.sql",
    ],
    cells: [
      { file_path: "src/payments/refund.ts", bucket: 1, intensity: 0.3, events: 6 },
      { file_path: "src/payments/refund.ts", bucket: 2, intensity: 0.8, events: 18 },
      { file_path: "src/payments/refund.ts", bucket: 3, intensity: 0.9, events: 22 },
      { file_path: "src/payments/refund.ts", bucket: 5, intensity: 0.6, events: 12 },
      { file_path: "src/payments/refund.ts", bucket: 8, intensity: 0.4, events: 7 },
      { file_path: "src/payments/validators.ts", bucket: 2, intensity: 0.5, events: 9 },
      { file_path: "src/payments/validators.ts", bucket: 6, intensity: 0.7, events: 14 },
      { file_path: "src/payments/__tests__/refund.test.ts", bucket: 4, intensity: 0.7, events: 15 },
      { file_path: "src/payments/__tests__/refund.test.ts", bucket: 7, intensity: 0.9, events: 21 },
      { file_path: "src/payments/__tests__/refund.test.ts", bucket: 10, intensity: 0.5, events: 10 },
      { file_path: "src/queue/worker.ts", bucket: 3, intensity: 0.2, events: 3 },
      { file_path: "src/queue/worker.ts", bucket: 9, intensity: 0.4, events: 6 },
      { file_path: "src/db/schema.sql", bucket: 1, intensity: 0.2, events: 2 },
      { file_path: "src/db/schema.sql", bucket: 6, intensity: 0.3, events: 4 },
    ],
    started_at: STARTED_AT,
    ended_at: ENDED_AT,
    totals_by_kind: {
      file_open: 19,
      edit: 47,
      test_run: 6,
      ai_prompt: 11,
      ai_accept: 4,
      commit: 5,
    },
  },
};
